### ISSUE TITLE
Could not Parse JSON in file

### ISSUE THREAD

**Issue by erw13n** [UpendoVentures/generator-upendodnn#31]
## Describe the bug
Error happen when creating SPA module.
Also mention at https://github.com/mtrutledge/generator-dnn/issues/72

## To Reproduce
Run **yo upendodnn** :
1. Create a Solution
2. Create SPA module
3. Fill in information

## Screenshots
![image](https://user-images.githubusercontent.com/792847/62167657-ed80b680-b34d-11e9-9b6f-6b4ffb1949dd.png)

## Errors
Error: Could not parse JSON in file: J:\\___NEIL\DEVELOPMENT\nationwidecaravanninguk\Modules\MySpa\package.json. Detail: Unexpected token _ in JSON at position 142
    at EditionInterface.module.exports [as readJSON] (C:\Users\erwin\AppData\Roaming\npm\node_modules\generator-upendodnn\node_modules\mem-fs-editor\lib\actions\read-json.js:8:13)
    at EditionInterface.module.exports [as extendJSON] (C:\Users\erwin\AppData\Roaming\npm\node_modules\generator-upendodnn\node_modules\mem-fs-editor\lib\actions\extend-json.js:6:30)
    at module.exports.writing (C:\Users\erwin\AppData\Roaming\npm\node_modules\generator-upendodnn\generators\spa\index.js:331:13)
    at Object.<anonymous> (C:\Users\erwin\AppData\Roaming\npm\node_modules\generator-upendodnn\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Users\erwin\AppData\Roaming\npm\node_modules\generator-upendodnn\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\erwin\AppData\Roaming\npm\node_modules\generator-upendodnn\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\erwin\AppData\Roaming\npm\node_modules\generator-upendodnn\node_modules\yeoman-generator\lib\index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\erwin\AppData\Roaming\npm\node_modules\generator-upendodnn\node_modules\yeoman-generator\lib\index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by erw13n** [comment]
Found it.

Error happen when I set "root path of DNN site" to *J:\\___NEIL\something\something*
Temp solution : Set it to an Escape String *J:\\\\__NEIL\\\\something\\\\something*

close this issue.
